import type { Product, CustomerLTV, PetProfile, Order } from "@/types";

export const MOCK_PET: PetProfile = {
  id: "pet_1",
  userId: "user_1",
  name: "Copérnico",
  species: "DOG",
  breed: "Golden Retriever",
  birthDate: new Date("2021-03-15"),
  adoptionDate: new Date("2021-05-09"),
  weight: 28.5,
  profilePhotoUrl: undefined,
  gender: "MALE",
  energyLevel: "ACTIVE",
  foodAllergies: ["pollo", "gluten"],
  foodPreferences: ["grain-free", "orgánico"],
  fears: ["FIREWORKS", "THUNDERSTORMS"],
  isNeutered: true,
  createdAt: new Date("2021-05-09"),
};

export const MOCK_USER = {
  id: "user_1",
  name: "César Andrés",
  email: "andresgarcia04cesar@gmail.com",
  role: "CLIENT" as const,
  ltv: 4230,
  orderCount: 12,
  totalSpent: 4230,
  avatarUrl: undefined,
  pets: [MOCK_PET],
  createdAt: new Date("2021-05-09"),
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod_1",
    name: "Premio Orgánico Sin Gluten",
    slug: "premio-organico-sin-gluten",
    description:
      "Snack artesanal elaborado con ingredientes 100% orgánicos certificados. Sin gluten, sin conservadores artificiales. Ideal para perros sensibles con alergias.",
    shortDescription: "Snack natural orgánico, libre de gluten y conservadores",
    price: 189,
    comparePrice: 249,
    imageUrls: [],
    category: "TREATS",
    targetSpecies: ["DOG"],
    energyLevels: ["ACTIVE", "ATHLETE"],
    allergenFree: ["gluten", "pollo", "soya"],
    tags: ["orgánico", "sin-gluten", "natural", "artesanal"],
    stock: 45,
    isActive: true,
    isFeatured: true,
    salesCount: 1240,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: "prod_2",
    name: "Suplemento Omega-3 Premium",
    slug: "suplemento-omega-3-premium",
    description:
      "Aceite de salmón de alta pureza para piel brillante, articulaciones saludables y sistema inmune fuerte. Formulado para perros y gatos.",
    shortDescription: "Aceite de salmón puro para piel, articulaciones e inmunidad",
    price: 349,
    comparePrice: 450,
    imageUrls: [],
    category: "SUPPLEMENTS",
    targetSpecies: ["DOG", "CAT"],
    energyLevels: ["SEDENTARY", "ACTIVE", "ATHLETE"],
    allergenFree: ["gluten", "lactosa"],
    tags: ["omega-3", "piel", "articulaciones", "premium"],
    stock: 28,
    isActive: true,
    isFeatured: true,
    salesCount: 876,
    rating: 4.8,
    reviewCount: 198,
  },
  {
    id: "prod_3",
    name: "Juguete Kong Extreme XL",
    slug: "juguete-kong-extreme-xl",
    description:
      "Juguete ultra-resistente de hule natural para perros con mucha energía. Rellena con snacks para horas de entretenimiento. Aguanta mordeduras fuertes.",
    shortDescription: "Juguete rellenable ultra-resistente para perros activos",
    price: 299,
    comparePrice: undefined,
    imageUrls: [],
    category: "TOYS",
    targetSpecies: ["DOG"],
    energyLevels: ["ACTIVE", "ATHLETE"],
    allergenFree: [],
    tags: ["juguete", "resistente", "activo", "entretenimiento"],
    stock: 15,
    isActive: true,
    isFeatured: false,
    salesCount: 654,
    rating: 4.7,
    reviewCount: 143,
  },
  {
    id: "prod_4",
    name: "Cama Ortopédica Memory Foam",
    slug: "cama-ortopedica-memory-foam",
    description:
      "Cama premium con espuma de memoria ortopédica. Funda removible y lavable en lavadora. Ideal para razas grandes y perros en etapa senior.",
    shortDescription: "Espuma de memoria ortopédica con funda lavable en lavadora",
    price: 1299,
    comparePrice: 1699,
    imageUrls: [],
    category: "ACCESSORIES",
    targetSpecies: ["DOG", "CAT"],
    energyLevels: ["SEDENTARY", "ACTIVE"],
    allergenFree: [],
    tags: ["ortopédica", "premium", "descanso", "lavable"],
    stock: 8,
    isActive: true,
    isFeatured: true,
    salesCount: 421,
    rating: 4.9,
    reviewCount: 87,
  },
  {
    id: "prod_5",
    name: "Shampoo Natural de Avena",
    slug: "shampoo-natural-avena",
    description:
      "Shampoo hipoalergénico con avena coloidal, aloe vera y aceite de coco. Sin sulfatos ni parabenos. Formulado para pieles sensibles y secas.",
    shortDescription: "Hipoalergénico con avena y aloe. Sin sulfatos ni parabenos",
    price: 249,
    comparePrice: undefined,
    imageUrls: [],
    category: "GROOMING",
    targetSpecies: ["DOG", "CAT"],
    energyLevels: ["SEDENTARY", "ACTIVE", "ATHLETE"],
    allergenFree: ["gluten", "sulfatos", "parabenos"],
    tags: ["natural", "hipoalergénico", "grooming", "suave"],
    stock: 32,
    isActive: true,
    isFeatured: false,
    salesCount: 789,
    rating: 4.6,
    reviewCount: 201,
  },
  {
    id: "prod_6",
    name: "Calming Drops Manzanilla",
    slug: "calming-drops-manzanilla",
    description:
      "Suplemento natural con manzanilla, valeriana y extracto de cáñamo (0% THC). Alivia la ansiedad por pirotecnia, viajes y tormentas eléctricas.",
    shortDescription: "Alivio natural para ansiedad por pirotecnia, tormentas y viajes",
    price: 389,
    comparePrice: 489,
    imageUrls: [],
    category: "CALMING",
    targetSpecies: ["DOG", "CAT"],
    energyLevels: ["SEDENTARY", "ACTIVE", "ATHLETE"],
    allergenFree: ["gluten", "pollo"],
    tags: ["calming", "ansiedad", "natural", "pirotecnia"],
    stock: 21,
    isActive: true,
    isFeatured: true,
    salesCount: 1100,
    rating: 4.8,
    reviewCount: 276,
  },
  {
    id: "prod_7",
    name: "Alimento Grain-Free Salmón",
    slug: "alimento-grain-free-salmon",
    description:
      "Alimento premium sin granos con salmón de Alaska como primer ingrediente. 70% proteína animal, sin fillers, maíz, trigo ni subproductos de pollo.",
    shortDescription: "70% proteína de salmón de Alaska. Sin granos, maíz ni pollo",
    price: 589,
    comparePrice: 720,
    imageUrls: [],
    category: "FOOD",
    targetSpecies: ["DOG"],
    energyLevels: ["ACTIVE", "ATHLETE"],
    allergenFree: ["gluten", "maíz", "trigo", "soya", "pollo"],
    tags: ["grain-free", "premium", "salmón", "proteína"],
    stock: 19,
    isActive: true,
    isFeatured: true,
    salesCount: 965,
    rating: 4.9,
    reviewCount: 224,
  },
  {
    id: "prod_8",
    name: "Collar LED Anti-extravío",
    slug: "collar-led-anti-extravio",
    description:
      "Collar inteligente con luz LED recargable por USB. Visible hasta 500m en la oscuridad. Resistente al agua IP67. Batería de hasta 8 horas.",
    shortDescription: "LED recargable USB, visible 500m. Resistente al agua IP67",
    price: 449,
    comparePrice: undefined,
    imageUrls: [],
    category: "ACCESSORIES",
    targetSpecies: ["DOG", "CAT"],
    energyLevels: ["ACTIVE", "ATHLETE"],
    allergenFree: [],
    tags: ["seguridad", "LED", "nocturno", "resistente"],
    stock: 13,
    isActive: true,
    isFeatured: false,
    salesCount: 543,
    rating: 4.5,
    reviewCount: 118,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord_1",
    orderNumber: "PU-2024-001847",
    userId: "user_1",
    status: "DELIVERED",
    subtotal: 1038,
    discount: 0,
    shipping: 99,
    tax: 0,
    total: 1137,
    items: [
      {
        id: "item_1",
        productId: "prod_1",
        product: MOCK_PRODUCTS[0],
        quantity: 2,
        unitPrice: 189,
        total: 378,
      },
      {
        id: "item_2",
        productId: "prod_4",
        product: MOCK_PRODUCTS[3],
        quantity: 1,
        unitPrice: 1299,
        total: 1299,
      },
    ],
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "ord_2",
    orderNumber: "PU-2024-002134",
    userId: "user_1",
    status: "SHIPPED",
    subtotal: 978,
    discount: 97,
    shipping: 0,
    tax: 0,
    total: 881,
    items: [
      {
        id: "item_3",
        productId: "prod_6",
        product: MOCK_PRODUCTS[5],
        quantity: 1,
        unitPrice: 389,
        total: 389,
      },
      {
        id: "item_4",
        productId: "prod_7",
        product: MOCK_PRODUCTS[6],
        quantity: 1,
        unitPrice: 589,
        total: 589,
      },
    ],
    createdAt: new Date("2024-04-18"),
  },
  {
    id: "ord_3",
    orderNumber: "PU-2024-002380",
    userId: "user_1",
    status: "PENDING",
    subtotal: 299,
    discount: 0,
    shipping: 99,
    tax: 0,
    total: 398,
    items: [
      {
        id: "item_5",
        productId: "prod_3",
        product: MOCK_PRODUCTS[2],
        quantity: 1,
        unitPrice: 299,
        total: 299,
      },
    ],
    createdAt: new Date("2024-04-23"),
  },
];

export const MOCK_CUSTOMERS: CustomerLTV[] = [
  {
    userId: "cust_1",
    userName: "Ana García Herrera",
    email: "ana.garcia@gmail.com",
    ltv: 12450,
    totalOrders: 34,
    avgOrderValue: 366,
    lastOrderDate: new Date("2024-04-20"),
    petCount: 2,
    primarySpecies: "DOG",
    tier: "PLATINUM",
    retentionRisk: "LOW",
  },
  {
    userId: "cust_2",
    userName: "Carlos Mendoza Vega",
    email: "cmendoza@outlook.com",
    ltv: 8920,
    totalOrders: 28,
    avgOrderValue: 319,
    lastOrderDate: new Date("2024-04-15"),
    petCount: 1,
    primarySpecies: "CAT",
    tier: "GOLD",
    retentionRisk: "LOW",
  },
  {
    userId: "cust_3",
    userName: "María López Sánchez",
    email: "mlopez@yahoo.com",
    ltv: 6780,
    totalOrders: 19,
    avgOrderValue: 357,
    lastOrderDate: new Date("2024-03-28"),
    petCount: 1,
    primarySpecies: "DOG",
    tier: "GOLD",
    retentionRisk: "MEDIUM",
  },
  {
    userId: "cust_4",
    userName: "Roberto Torres Cruz",
    email: "rtorres@gmail.com",
    ltv: 4230,
    totalOrders: 15,
    avgOrderValue: 282,
    lastOrderDate: new Date("2024-04-10"),
    petCount: 2,
    primarySpecies: "DOG",
    tier: "SILVER",
    retentionRisk: "LOW",
  },
  {
    userId: "cust_5",
    userName: "Sofía Ramírez Fuentes",
    email: "sofia.rf@gmail.com",
    ltv: 2890,
    totalOrders: 11,
    avgOrderValue: 263,
    lastOrderDate: new Date("2024-03-15"),
    petCount: 1,
    primarySpecies: "DOG",
    tier: "SILVER",
    retentionRisk: "MEDIUM",
  },
  {
    userId: "cust_6",
    userName: "Diego Martínez Alba",
    email: "diego.m@hotmail.com",
    ltv: 1560,
    totalOrders: 7,
    avgOrderValue: 223,
    lastOrderDate: new Date("2024-02-20"),
    petCount: 1,
    primarySpecies: "CAT",
    tier: "SILVER",
    retentionRisk: "HIGH",
  },
  {
    userId: "cust_7",
    userName: "Laura Sánchez Peña",
    email: "laura.sp@gmail.com",
    ltv: 890,
    totalOrders: 4,
    avgOrderValue: 223,
    lastOrderDate: new Date("2024-03-05"),
    petCount: 1,
    primarySpecies: "DOG",
    tier: "BRONZE",
    retentionRisk: "MEDIUM",
  },
  {
    userId: "cust_8",
    userName: "José Herrera Campos",
    email: "jherrera@gmail.com",
    ltv: 450,
    totalOrders: 2,
    avgOrderValue: 225,
    lastOrderDate: new Date("2024-01-28"),
    petCount: 1,
    primarySpecies: "DOG",
    tier: "BRONZE",
    retentionRisk: "HIGH",
  },
];

export const REVENUE_DATA = [
  { mes: "Nov", ingresos: 185420, ordenes: 654, clientes: 489 },
  { mes: "Dic", ingresos: 234890, ordenes: 847, clientes: 612 },
  { mes: "Ene", ingresos: 198760, ordenes: 712, clientes: 534 },
  { mes: "Feb", ingresos: 215340, ordenes: 763, clientes: 571 },
  { mes: "Mar", ingresos: 228920, ordenes: 821, clientes: 615 },
  { mes: "Abr", ingresos: 241580, ordenes: 847, clientes: 643 },
];

export const METRICS = {
  revenueTotal: 241580,
  revenueGrowth: 5.5,
  ordersTotal: 847,
  ordersGrowth: 3.2,
  avgLTV: 3420,
  ltvGrowth: 8.1,
  retentionRate: 73,
  retentionGrowth: -1.2,
};

export const CATEGORY_EMOJIS: Record<string, string> = {
  TREATS: "🦴",
  SUPPLEMENTS: "🌿",
  TOYS: "🎾",
  ACCESSORIES: "🛍️",
  GROOMING: "🧴",
  CALMING: "💧",
  FOOD: "🐟",
  HEALTH: "💊",
  APPAREL: "👕",
};
